### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by gptsahil** [kartikchaudhari/BigGrocery#2]
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/1049): Unknown database 'biggrocer'

Filename: mysqli/mysqli_driver.php

Line Number: 201

Backtrace:

File: C:\xampp\htdocs\BigGrocery-master\application\core\My_Controller.php
Line: 7
Function: __construct

File: C:\xampp\htdocs\BigGrocery-master\index.php
Line: 315
Function: require_once

A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: C:/xampp/htdocs/BigGrocery-master/system/database/DB_driver.php

Line Number: 436

**Comment by kartikchaudhari** [comment]
you'll need sql file to setup database "biggrocer", I will  mail you sql file as early as possible.

**Comment by gptsahil** [comment]
Thank you so much.
